### ISSUE TITLE
Give users options to write 'notes' about school programs

### ISSUE THREAD

**Issue by Mattwalsh129** [ghing/learning-collaborative-maps#16]
This could be helpful to say how long they are at the school

**Comment by ghing** [comment]
The notes would be for a program? That is, part of the "add program" form? Or would they be notes about a school that may or may not be about a program?

**Comment by Mattwalsh129** [comment]
It would be part of the add program form, just more optional information to post about.

**Comment by Mattwalsh129** [comment]
To clarify more: that we want folks to include their program dates in that section

**Comment by Mattwalsh129** [comment]
I am not sure what iteration 3 means, but I am still very interested in this

**Comment by ghing** [comment]
Iteration 3 means happening this week.  Iterations are just a chunk of work.

**Comment by ghing** [comment]
Just deployed this into production.
