### ISSUE TITLE
Have the add program form be an option but not present on every school

### ISSUE THREAD

**Issue by Mattwalsh129** [ghing/learning-collaborative-maps#17]
Does that make sense

**Comment by ghing** [comment]
Do you mean you want to hide the form until the user clicks something?

**Comment by Mattwalsh129** [comment]
Yes

**Comment by ghing** [comment]
Adding this to Iteration 4 because this functionality makes sense to implement alongside the editing of programs.

**Comment by Mattwalsh129** [comment]
Whoops. So now when you 'add program' it now is too big and gets clunky at
the bottom.

On Tue, May 3, 2016 at 10:15 PM, Geoffrey Hing <notifications@github.com>
wrote:

> Closed #17
> <https://github.com/ghing/learning-collaborative-maps/issues/17> via
> 85ab2ec
> <https://github.com/ghing/learning-collaborative-maps/commit/85ab2ec7a0291b7e16c4ef8e8aaf8f749f34b2c7>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ghing/learning-collaborative-maps/issues/17#event-649678294>
>



-- 
Matthew Kennedy  Walsh

**Comment by Mattwalsh129** [comment]
So this is only for schools that occupy two lines of text.
AND
This add program button only exists at the beginning so when you click on a
new school you get the full form. Does that make sense?

On Tue, May 3, 2016 at 10:26 PM, Matt Walsh <mattwalsh129@gmail.com> wrote:

> Whoops. So now when you 'add program' it now is too big and gets clunky at
> the bottom.
>
> On Tue, May 3, 2016 at 10:15 PM, Geoffrey Hing <notifications@github.com>
> wrote:
>
>> Closed #17
>> <https://github.com/ghing/learning-collaborative-maps/issues/17> via
>> 85ab2ec
>> <https://github.com/ghing/learning-collaborative-maps/commit/85ab2ec7a0291b7e16c4ef8e8aaf8f749f34b2c7>
>> .
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ghing/learning-collaborative-maps/issues/17#event-649678294>
>>
>
>
>
> --
> Matthew Kennedy  Walsh
>



-- 
Matthew Kennedy  Walsh

**Comment by ghing** [comment]
I'm not sure what you mean.  If something looks weird can you add a screenshot?  

Also, it's important to keep the logic simple and consistent.  The solution I chose was to hide the form initially for all schools. It takes an extra click in some cases, but I don't think that's too annoying.

**Comment by Mattwalsh129** [comment]
Sounds good. So this is what I am seeing. What is interesting is that I am
on a different computer so it totally has to do with screen size but on my
laptop this is what it looks like.

[image: Inline image 1][image: Inline image 2]

On Tue, May 3, 2016 at 10:31 PM, Geoffrey Hing <notifications@github.com>
wrote:

> I'm not sure what you mean. If something looks weird can you add a
> screenshot?
>
> Also, it's important to keep the logic simple and consistent. The solution
> I chose was to hide the form initially for all schools. It takes an extra
> click in some cases, but I don't think that's too annoying.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ghing/learning-collaborative-maps/issues/17#issuecomment-216733392>
>



-- 
Matthew Kennedy  Walsh

**Comment by ghing** [comment]
I don't think that image finished uploading.  Can you try re-uploading the screenshot?

**Comment by Mattwalsh129** [comment]
Here they are again, also sent them to your email:
[image: Inline image 2][image: Inline image 1]

On Wed, May 4, 2016 at 10:41 AM, Geoffrey Hing <notifications@github.com>
wrote:

> I don't think that image finished uploading. Can you try re-uploading the
> screenshot?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ghing/learning-collaborative-maps/issues/17#issuecomment-216906329>
>



-- 
Matthew Kennedy  Walsh
