### ISSUE TITLE
Alphabatize Programs

### ISSUE THREAD

**Issue by Mattwalsh129** [ghing/learning-collaborative-maps#19]
Can we have between friends be put into the alphabetical order in the add program function? It would also be cool if it was blank then you got the pull down options.

**Comment by Mattwalsh129** [comment]
I guess going along with the 'blank' function. Could everything revert back to original after you have entered a program rather than have it remaining there?

**Comment by ghing** [comment]
I implemented the "blank" default and alphabetization of the agency names,

However, I couldn't get reset of the elements to work.  I have a question about how to do this open at http://stackoverflow.com/questions/36458287/how-do-i-reset-select-elements-in-a-react-form-after-submission
