### ISSUE TITLE
Load private schools

### ISSUE THREAD

**Issue by Mattwalsh129** [ghing/learning-collaborative-maps#21]
How easy is it to add a school?
For instance Josephinum Academy in wicker park is not on the list.

**Comment by ghing** [comment]
That's because it's a private school and that's in a separate dataset.  I can add those at some point.

**Comment by ghing** [comment]
Changed title from "Adding schools" to "Load private schools" to more precisely reflect the issue.

**Comment by ghing** [comment]
Should we just load all private schools in Cook County?

**Comment by Mattwalsh129** [comment]
Yes lets just add the private schools in cook county. But probably be
prepared to add them in the neighboring communities

On Thu, Apr 7, 2016 at 12:57 PM, Geoffrey Hing <notifications@github.com>
wrote:

> Should we just load all private schools in Cook County?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ghing/learning-collaborative-maps/issues/21#issuecomment-207028537>
>



-- 
Matthew Kennedy  Walsh

**Comment by ghing** [comment]
Can you get me a list of cities or counties?  It will be easier to just geocode and load all at once than one-by-one.

**Comment by Mattwalsh129** [comment]
Buffalo Grove, Highland Park, Wheaton, Lake Zurich, Elmhurst, Oak Brook,
Downers Grove, Carol Stream

This is just a guess though, I won't have a definitive list till I see
these people tomorrow.

On Thu, Apr 7, 2016 at 1:09 PM, Geoffrey Hing <notifications@github.com>
wrote:

> Can you get me a list of cities or counties? It will be easier to just
> geocode and load all at once than one-by-one.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ghing/learning-collaborative-maps/issues/21#issuecomment-207032331>
>



-- 
Matthew Kennedy  Walsh

**Comment by Mattwalsh129** [comment]
The one organization says they work in Dupage county (in there application)

The other says Lake County but I don't know if they reach the top of Lake
County?

On Thu, Apr 7, 2016 at 1:20 PM, Matt Walsh <mattwalsh129@gmail.com> wrote:

> Buffalo Grove, Highland Park, Wheaton, Lake Zurich, Elmhurst, Oak Brook,
> Downers Grove, Carol Stream
>
> This is just a guess though, I won't have a definitive list till I see
> these people tomorrow.
>
> On Thu, Apr 7, 2016 at 1:09 PM, Geoffrey Hing <notifications@github.com>
> wrote:
>
>> Can you get me a list of cities or counties? It will be easier to just
>> geocode and load all at once than one-by-one.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ghing/learning-collaborative-maps/issues/21#issuecomment-207032331>
>>
>
>
>
> --
> Matthew Kennedy  Walsh
>



-- 
Matthew Kennedy  Walsh
