### ISSUE TITLE
Editing Data

### ISSUE THREAD

**Issue by Mattwalsh129** [ghing/learning-collaborative-maps#28]
Hey,
What is the easiest way for me to change the data on the backend? Or even have it be something that anyone can do? Just for spelling errors and things?

**Comment by ghing** [comment]
There isn't currently a way to easily edit data in the backend.  Can you collect examples of edits in this ticket? Based on that, we can figure out the best way to implement this feature

**Comment by Mattwalsh129** [comment]
One example for me was when I was doing mass data entry I was not sure what
grades some people worked in so I put question marks.

On Mon, Apr 11, 2016 at 5:14 PM, Geoffrey Hing <notifications@github.com>
wrote:

> There isn't currently a way to easily edit data in the backend. Can you
> collect examples of edits in this ticket? Based on that, we can figure out
> the best way to implement this feature
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ghing/learning-collaborative-maps/issues/28#issuecomment-208588999>
>



-- 
Matthew Kennedy  Walsh

**Comment by ghing** [comment]
This has been implemented, but I want to do a little more testing before I deploy.

**Comment by ghing** [comment]
Deployed.

**Comment by Mattwalsh129** [comment]
Where has this been deployed/how to I have access to it?

On Wed, Jun 1, 2016 at 9:45 AM, Geoffrey Hing <notifications@github.com>
wrote:

> Closed #28
> <https://github.com/ghing/learning-collaborative-maps/issues/28>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ghing/learning-collaborative-maps/issues/28#event-678520458>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARceHD5908BST8foOQS0Ru7MdS16Q28-ks5qHZr9gaJpZM4IE2xX>
> .
>



-- 
Matthew Kennedy  Walsh

**Comment by ghing** [comment]
The main site.  To edit a program, you just need to mouse over the program in the list and an "edit" link will appear.

<img width="419" alt="screen shot 2016-06-01 at 3 51 28 pm" src="https://cloud.githubusercontent.com/assets/110420/15725274/bcb08cfe-2810-11e6-814b-2838708bfd5e.png">

**Comment by Mattwalsh129** [comment]
Great thanks. I did not see that/understand that was how it was working

On Wed, Jun 1, 2016 at 3:51 PM, Geoffrey Hing <notifications@github.com>
wrote:

> The main site. To edit a program, you just need to mouse over the program
> in the list and an "edit" link will appear.
>
> [image: screen shot 2016-06-01 at 3 51 28 pm]
> <https://cloud.githubusercontent.com/assets/110420/15725274/bcb08cfe-2810-11e6-814b-2838708bfd5e.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ghing/learning-collaborative-maps/issues/28#issuecomment-223120796>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARceHNJW0sBPw1M2pf2WvvtpItJK6O31ks5qHfDkgaJpZM4IE2xX>
> .
>



-- 
Matthew Kennedy  Walsh

**Comment by Mattwalsh129** [comment]
Hey,
So the hover over option does not work on Ipads. I am wondering if it would be worth just having the edit button always be present?
