### ISSUE TITLE
Low Priority - Making note of years programs existed

### ISSUE THREAD

**Issue by Mattwalsh129** [ghing/learning-collaborative-maps#30]
What will the method be to see that we worked in a school a previous year but not this current year.

**Comment by ghing** [comment]
I think adding a dates field to the program records (#31) is the best way.

**Comment by Mattwalsh129** [comment]
Makes sense to me.

On Mon, Apr 11, 2016 at 5:18 PM, Geoffrey Hing <notifications@github.com>
wrote:

> I think adding a dates field to the program records (#31
> <https://github.com/ghing/learning-collaborative-maps/issues/31>) is the
> best way.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ghing/learning-collaborative-maps/issues/30#issuecomment-208590382>
>



-- 
Matthew Kennedy  Walsh

**Comment by ghing** [comment]
Closing this.  Will address this in #31.
