### ISSUE TITLE
Adding Dates of programming

### ISSUE THREAD

**Issue by Mattwalsh129** [ghing/learning-collaborative-maps#31]
A lot of people were asking to have the dates of the program be put in as an option. I am imagining them being able to choose a month the program happened or the season.

**Comment by ghing** [comment]
Can you find out how people would want to enter this?  Or we can just add it as a free text field and see how people enter it.

**Comment by Mattwalsh129** [comment]
What people said when it was discussed was month or season. I like the free
text field section and give options that say (month, quarter, season,
semester, etc) and see what happens from there.

On Mon, Apr 11, 2016 at 5:12 PM, Geoffrey Hing <notifications@github.com>
wrote:

> Can you find out how people would want to enter this? Or we can just add
> it as a free text field and see how people enter it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ghing/learning-collaborative-maps/issues/31#issuecomment-208587396>
>



-- 
Matthew Kennedy  Walsh

**Comment by Mattwalsh129** [comment]
I am not sure if I can, but I would love to make this another High Priority thing and say that the 3 things that are high priority are the ones that would be great to be done by the end of the week when I email all of the contacts with a link and a more detailed explanation of this?

**Comment by ghing** [comment]
I think realistically I can do one to two things that are high priority this week.
