### ISSUE TITLE
The program data is missing

### ISSUE THREAD

**Issue by Mattwalsh129** [ghing/learning-collaborative-maps#41]
So if you click on a school that is colored none of the info is there. It only shows up before you click 'add program'

**Comment by ghing** [comment]
I'm not able to replicate this.  Seems to be working for me:

<img width="1424" alt="screen shot 2016-05-10 at 3 11 07 pm" src="https://cloud.githubusercontent.com/assets/110420/15160899/80c99b1e-16c1-11e6-9ed7-c4ac013fc423.png">

Is there a particular school that you can tell me to try to replicate this?

**Comment by Mattwalsh129** [comment]
Once you click the 'add program' button it is gone. and if you were to
click around it continues as such:
[image: Inline image 1]

On Tue, May 10, 2016 at 3:12 PM, Geoffrey Hing <notifications@github.com>
wrote:

> I'm not able to replicate this. Seems to be working for me:
>
> [image: screen shot 2016-05-10 at 3 11 07 pm]
> <https://cloud.githubusercontent.com/assets/110420/15160899/80c99b1e-16c1-11e6-9ed7-c4ac013fc423.png>
>
> Is there a particular school that you can tell me to try to replicate this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ghing/learning-collaborative-maps/issues/41#issuecomment-218276583>
>



-- 
Matthew Kennedy  Walsh

**Comment by ghing** [comment]
If you finish adding the program, it will once again show the list.  If you click "Cancel" it will hide the add program form and show the list.  Perhaps it would make sense to have it always revert to the list when you click on a new school, even if the add program list hasn't been cancelled.

**Comment by Mattwalsh129** [comment]
I think i understand what you mean and I agree that it should revert back

**Comment by Mattwalsh129** [comment]
Following up on this

**Comment by Mattwalsh129** [comment]
I am not sure if this is working for me?
The idea would be that when I clicked on a new school it would revert back
to the original not the edit program item?

On Wed, Jun 1, 2016 at 8:59 PM, Geoffrey Hing <notifications@github.com>
wrote:

> Closed #41
> <https://github.com/ghing/learning-collaborative-maps/issues/41> via
> 0e76886
> <https://github.com/ghing/learning-collaborative-maps/commit/0e76886643823158d5c8188377918c347f040694>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ghing/learning-collaborative-maps/issues/41#event-679245930>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARceHPNZPHf7l0aGXq9luZcHOTAWdbuUks5qHjjzgaJpZM4IbdcC>
> .
>



-- 
Matthew Kennedy  Walsh

**Comment by ghing** [comment]
Haven't deployed this yet

**Comment by ghing** [comment]
Deployed!
