### ISSUE TITLE
Adding another Agency

### ISSUE THREAD

**Issue by Mattwalsh129** [ghing/learning-collaborative-maps#67]
Can we add BAM to the agency list, its can be any basic color.

**Comment by ghing** [comment]
Should the agency be listed as "BAM" or is it an acronym that should be spelled out?  I can update this in the next few days if you give me an answer.

**Comment by Mattwalsh129** [comment]
It could be BAM (Becoming a Man)

**Comment by ghing** [comment]
I should probably just implement #59 and add these through the admin interface.

**Comment by Mattwalsh129** [comment]
Hey,
Somehow we missed adding an agency, can you add: Heartland Human Care Services. If you do this in the next 24 hours then I can email them, if not do you mind emailing Pam when it is done because I will be on vacation.

**Comment by ghing** [comment]
I added these manually.  You should see them in the production site.
