### ISSUE TITLE
Agency fields don't show up when edit page accessed directly

### ISSUE THREAD

**Issue by ghing** [ghing/learning-collaborative-maps#71]
## To replicate

Log in

Navigate to `/admin/agencies/apna-ghar`

## Expected results

Fields for this agency are shown in the form

## Observed results

Fields for the agency are empty

## Suspected problem

The agency to be edited is passed as a prop from `AgencyAdmin` to `AgencyAdminForm`.  In the constructor of `AgencyAdminForm`, this is used to set internal state used to render the values of the form inputs:

```
    if (props.agency) {
      const coords = props.agency.geometry.coordinates;
      const agencyProps = props.agency.properties;
      console.log(agencyProps);

      this.state.slug = agencyProps.slug;
      this.state.slugDisabled = true;
      this.state.agency = agencyProps.agency;
      this.state.catchment_area = agencyProps.catchment_area;
      this.state.program_type = agencyProps.program_type;
      this.state.office_location = agencyProps.office_location;
      this.state.marker_color = agencyProps.marker_color;

      this.state.lat = coords[1];
      this.state.lng = coords[0];
    }
```

This all works fine if we first visit any page except for `/admin/agency/:slug`, because the agencies are fetched and set in `AgencyStore` by the time we navigate to the agency editing page.  That is, the agency to be edited is available by the time `AgencyStore` is constructed.

However, if we visit `/admin/agency/:slug` as the first page, the agency to be edited is not yet available when the `AgencyAdminForm` is constructed.  Although `AgencyAdmin` handles the change event from `AgencyStore` and updates the `agency` prop passed to `AgencyAdminForm` and it is re-rendered, the internal state of `AgencyAdminForm` is only set once, on construction.

## Solution

This is an example of why it's generally bad practice to set state from props.  What we need to do is [lift the state up](https://facebook.github.io/react/docs/lifting-state-up.html) from `AgencyAdminForm` into `AgencyAdmin`.

## Notes

This was originally discovered as part of implementing #59.

This likely affects editing schools as well.

**Comment by Mattwalsh129** [comment]
I am not really sure what this means but I am happy to talk more about it!

**Comment by ghing** [comment]
This is just an internal bug report that I made for a bug I discovered
while working on the admin interface.
